### ISSUE TITLE
给您推荐 niagaralauncher.app

### ISSUE THREAD

**Issue by E-one-LLC** [huzhicheng/ALauncher#1]
给您推荐 niagaralauncher.app

**Comment by huzhicheng** [comment]
用过这个，差别还是挺大的

**Comment by E-one-LLC** [comment]
> 用过这个，差别还是挺大的

同 [Olauncher](https://github.com/tanujnotes/Olauncher) 类型的 这里还有一个  [YAM_LAUNCHER](github.com/ottop/yam_launcher)

**Comment by E-one-LLC** [comment]
> 用过这个，差别还是挺大的

像您学习，以后，就用您这个 来练练手。。
